### ISSUE TITLE
How do I open the tool shown in the screenshot?

### ISSUE THREAD

**Issue by terazik-mubaloo** [gatopeich/Wiimote-2022#1]
I hope this isnt too dumb of a question, but i dont see how im supposed to open the mapping tool shown in the screenshot. Ive followed the installation instructions, but no such thing has been installed. So its not too much of a problem, since i can still technically use my wiimote+nunchuk on steam, but things like the vertical axis of the nunchuck's joystick just dont want to map to the controller, so itd be really nice if i could access the tool who's purpose is to do so.

**Comment by gatopeich** [comment]
I think it was jstest-gtk

**Comment by terazik-mubaloo** [comment]
thats it, thanks!
